apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailinfoapp
  namespace: emailinfoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: emailinfoapp
        image: email_info_app:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name:  emailinfoappservice
  namespace: emailinfoapp
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
